// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGQ54aNMyyOV9m3Lr3NwuyUH9ufwmiYVk',
    appId: '1:806606295370:web:72cc532f52af002d4431b3',
    messagingSenderId: '806606295370',
    projectId: 'spotifyappclone02',
    authDomain: 'spotifyappclone02.firebaseapp.com',
    storageBucket: 'spotifyappclone02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsD5MwDZriRglcY0gKajna-U2gyRJi1bs',
    appId: '1:806606295370:android:819230ec8645978a4431b3',
    messagingSenderId: '806606295370',
    projectId: 'spotifyappclone02',
    storageBucket: 'spotifyappclone02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgHs_EPFYCO2xZlUxUjMCd9Lar40CHFQI',
    appId: '1:806606295370:ios:5c2c68715d75d0bf4431b3',
    messagingSenderId: '806606295370',
    projectId: 'spotifyappclone02',
    storageBucket: 'spotifyappclone02.firebasestorage.app',
    iosBundleId: 'com.example.spotifyCloneApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgHs_EPFYCO2xZlUxUjMCd9Lar40CHFQI',
    appId: '1:806606295370:ios:5c2c68715d75d0bf4431b3',
    messagingSenderId: '806606295370',
    projectId: 'spotifyappclone02',
    storageBucket: 'spotifyappclone02.firebasestorage.app',
    iosBundleId: 'com.example.spotifyCloneApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGQ54aNMyyOV9m3Lr3NwuyUH9ufwmiYVk',
    appId: '1:806606295370:web:5d791fe8cb47abab4431b3',
    messagingSenderId: '806606295370',
    projectId: 'spotifyappclone02',
    authDomain: 'spotifyappclone02.firebaseapp.com',
    storageBucket: 'spotifyappclone02.firebasestorage.app',
  );
}
